apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: slack
---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: slack-command
spec:
  protocol: http
  input: slack
  container:
    image: projectriff/slack-command:test
